/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "stm32g431xx.h"
#include "stm32g431xx_gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void)
{
	for(volatile uint32_t i = 0 ; i < 1000000; i++);
}

int main(void)
{
	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_PeriClockControl(GPIOC, ENABLE);

	GPIO_Handle_t GpioLed;
	printf("GpioLed Handler DONE OK\n");
	GpioLed.pGPIOx = GPIOA;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber 		= GPIO_PIN_NO_5;
	GpioLed.GPIO_PinConfig.GPIO_PinMode			= GPIO_MODE_OUTPUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed		= GPIO_SPEED_FAST;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType		= GPIO_OP_TYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl	= GPIO_NO_PUPD;

	printf("GpioLED structure:\n");
	printf("Pin:\t%d\n", GpioLed.GPIO_PinConfig.GPIO_PinNumber);
	printf("Mode:\t%d\n", GpioLed.GPIO_PinConfig.GPIO_PinMode);
	printf("Speed:\t%d\n", GpioLed.GPIO_PinConfig.GPIO_PinSpeed);
	printf("Type:\t%d\n", GpioLed.GPIO_PinConfig.GPIO_PinOPType);
	printf("Contr:\t%d\n", GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl);


	GPIO_Init(&GpioLed);

	GPIO_Handle_t Button;
	Button.pGPIOx = GPIOC;
	Button.GPIO_PinConfig.GPIO_PinNumber		= GPIO_PIN_NO_13;
	Button.GPIO_PinConfig.GPIO_PinMode			= GPIO_MODE_INPUT;
	Button.GPIO_PinConfig.GPIO_PinSpeed			= GPIO_SPEED_FAST;
	Button.GPIO_PinConfig.GPIO_PinOPType		= GPIO_OP_TYPE_PP;
	Button.GPIO_PinConfig.GPIO_PinPuPdControl	= GPIO_NO_PUPD;

	GPIO_Init(&Button);


	while(1)
	{
		delay();
		printf("Button Pressed\n");
		GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);

		/*if (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == 0)
		{
			delay();
			printf("Button Pressed\n");
			GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);
		}*/

	}
}
